config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
  end
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :line_items
  resources :equips
  root 'armory#index', as: 'armory_index'
  resources :armors do
    get :who_bought, on: :member
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/equip.rb
class Equip < ApplicationRecord
    has_many :line_items, dependent: :destroy
end

app/controllers/equips_controller.rb
class EquipsController < ApplicationController
  before_action :set_equip, only: %i[ show edit update destroy ]

  # GET /equips or /equips.json
  def index
    @equips = Equip.all
  end

  # GET /equips/1 or /equips/1.json
  def show
  end

  # GET /equips/new
  def new
    @equip = Equip.new
  end

  # GET /equips/1/edit
  def edit
  end

  # POST /equips or /equips.json
  def create
    @equip = Equip.new(equip_params)

    respond_to do |format|
      if @equip.save
        format.html { redirect_to equip_url(@equip), notice: "Equip was successfully created." }
        format.json { render :show, status: :created, location: @equip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equips/1 or /equips/1.json
  def update
    respond_to do |format|
      if @equip.update(equip_params)
        format.html { redirect_to equip_url(@equip), notice: "Equip was successfully updated." }
        format.json { render :show, status: :ok, location: @equip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equips/1 or /equips/1.json
  def destroy
    @equip.destroy!

    respond_to do |format|
      format.html { redirect_to equips_url, notice: "Equip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equip
      @equip = Equip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equip_params
      params.fetch(:equip, {})
    end
end

app/helpers/equips_helper.rb
module EquipsHelper
end

app/views/equips/_equip.html.erb
<div id="<%= dom_id equip %>">
    <h2 class="font-bold text-lg mb-3"> Current Equipment </h2>

    <ul class="list-disc list-inside">
        <% equip.line_items.each do |item| %>
        <% case item.armor.armor_type %>
            <% when "Plate" %>
              <li class="flex items-center space-x-2"><%= image_tag 'plate.gif', class: "w-10" %><span><%= item.armor.name %></span></li>
            <% when "Leather" %>
              <li class="flex items-center space-x-2"><%= image_tag 'leather.gif', class: "w-10" %><span><%= item.armor.name %></span></li>
            <% when "Chainmail" %>
              <li class="flex items-center space-x-2"><%= image_tag 'chainmail.gif', class: "w-10" %><span><%= item.armor.name %></span></li>
            <% when "Cloth" %>
              <li class="flex items-center space-x-2"><%= image_tag 'cloth.gif', class: "w-10" %><span><%= item.armor.name %></span></li>
            <% end %>
        <% end %>
    </ul>
</div>

app/views/equips/_form.html.erb
<%= form_with(model: equip) do |form| %>
  <% if equip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(equip.errors.count, "error") %> prohibited this equip from being saved:</h2>

      <ul>
        <% equip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/equips/edit.html.erb
<h1>Editing equip</h1>

<%= render "form", equip: @equip %>

<br>

<div>
  <%= link_to "Show this equip", @equip %> |
  <%= link_to "Back to equips", equips_path %>
</div>

app/views/equips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Equips</h1>

<div id="equips">
  <% @equips.each do |equip| %>
    <%= render equip %>
    <p>
      <%= link_to "Show this equip", equip %>
    </p>
  <% end %>
</div>

<%= link_to "New equip", new_equip_path %>

app/views/equips/new.html.erb
<h1>New equip</h1>

<%= render "form", equip: @equip %>

<br>

<div>
  <%= link_to "Back to equips", equips_path %>
</div>

app/views/equips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @equip %>

<div>
  <%= link_to "Edit this equip", edit_equip_path(@equip) %> |
  <%= link_to "Back to equips", equips_path %>

  <%= button_to "Destroy this equip", @equip, method: :delete %>
</div>