config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
  end
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :line_items
  resources :equips
  root 'armory#index', as: 'armory_index'
  resources :armors do
    get :who_bought, on: :member
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework6</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="relative min-h-screen">
  <div class="bg-image absolute inset-0 z-0" style="background-image: url(<%= asset_path('dndImage.jpeg') %>);"></div>

  <div class="relative z-10">
    <header class="bg-green-600 text-white p-4">
      <div class="max-w-6xl mx-auto flex justify-between items-center">
        <h1 class="font-bold p-10">Welcome To The Dragons Den</h1>
        <nav>
          <ul class="flex space-x-4">
            <li><%= link_to "Home", armory_index_path, class: "hover:underline" %></li> |
            <li><%= link_to "Armor", armors_path, class: "hover:underline" %></li> | 
            <li><%= link_to "Equip", equips_path, class: "hover:underline" %></li> |
            <li><%= link_to 'Sign Up', signup_path, class: 'hover:underline' %></li> |
            <li><%= link_to 'login', login_path, class: 'hover:underline'%></li>/
            <li><%= link_to 'Logout', logout_path, class: 'hover:underline' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </div>
</body>
</html>